name: ping_identity
description: A new flutter plugin project.
version: 0.1.1

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

  equatable: ^1.2.0
  json_annotation: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.10.0
  json_serializable: ^3.3.0

flutter:
  plugin:
    platforms:
      android:
        package: no.dnb.ping_identity
        pluginClass: PingIdentityPlugin
      ios:
        pluginClass: PingIdentityPlugin
