import 'package:json_annotation/json_annotation.dart';

enum PingIdentityErrorDomain {
  @JsonValue('PIDErrorUnknown')
  unknown,
  @JsonValue('PIDErrorWithPairing')
  pairing,
  @JsonValue('PIDErrorAppDisabled')
  appDisabled,
  @JsonValue('PIDErrorWrongAppID')
  wrongAppId,
  @JsonValue('PIDErrorTimeout')
  timeoutError,
  @JsonValue('PIDErrorNoInternetConnection')
  noInternetConnection,
  @JsonValue('PIDErrorWrongSignature')
  signature,
  @JsonValue('PIDErrorProblemWithPublicKey')
  publicKey,
  @JsonValue('PIDNetworkError')
  network,
  @JsonValue('PIDInternalError')
  internal,
  @JsonValue('PIDMissingPermissions')
  missingPermissions,
  @JsonValue('PIDErrorDeviceTokenIsMissing')
  deviceTokenMissing,
  @JsonValue('PIDErrorExpiredOrWrongAuthToken')
  expiredOrWrongAuthToken,
  @JsonValue('PIDErrorWrongAppIDFromAuthToken')
  wrongAppIdFromAuthToken,
  @JsonValue('PIDErrorWrongAccountIDFromAuthToken')
  wrongAccountIdFromAuthToken,
  @JsonValue('PIDErrorUserIsSuspended')
  userIsSuspended,
  @JsonValue('PIDErrorUsernameNotPairedForToken')
  usernameNotPairedForToken,
  @JsonValue('PIDErrorAuthTokenAlreadyUsed')
  authTokenAlreadyUsed,
  @JsonValue('PIDErrorServerResponse')
  serverResponse,
  @JsonValue('PIDErrorDeviceRooted')
  deviceRooted,
  @JsonValue('PIDErrorWithRepairing')
  rePairing,
  @JsonValue('PIDErrorWithRepairingTestOtp')
  rePairingTestOtp,
}
